### ISSUE TITLE
look for slots from today

### ISSUE THREAD

**Issue by bitshiftr** [pallupz/covid-vaccine-booking#58]
Few of the hospitals offer their slots early in the morning for the same day. The current script starts looking for slots from tomorrow, so we will need to change "check_calendar_by_district" and "check_calendar_by_pincode" to "today" instead of "tomorrow".

**Comment by bitshiftr** [comment]
FYI: to make it work for now until @pallupz gets a chance to change, here are the steps to make it work:

in the functions "check_calendar_by_district" and "check_calendar_by_pincode", create a new variable:
now = (today + datetime.timedelta(days=0)).strftime("%d-%m-%Y")

Replace "today" to "now" in this line in both the function mentioned above:
resp = requests.get(base_url.format(location['district_id'], now), headers=request_header)

and if you prefer, you change it in the print statement too.

**Comment by sharpant-dot** [comment]
did it work?

**Comment by sixfooter** [comment]
@bitshiftr if i am using a windows exe, how can i make it to work with new code. 
the exe was built using the old code that was released. any ideas?

**Comment by bitshiftr** [comment]
You will need to make the code changes and recompile it as an exe. I don't
use Windows, so can't help you with that.

**Comment by sixfooter** [comment]
sure, thanks, i did the changes but not sure how to recompile it. @pallupz , could you please list it for new users like me.

**Comment by pallupz** [comment]
@sixfooter you'd need ```pyinstaller``` package and run ```pyinstaller --onfile <yourfile.py>

**Comment by sixfooter** [comment]
thanks @pallupz , could you please ack if this is correct  : 
1. I could also use this in windows as well? 
2. In case of unix, i wouldnt then need to do a sudo [ as the co. policies may come in the way ] and still get the exe to compile?

**Comment by pallupz** [comment]
I use windows and it runs

**Comment by pallupz** [comment]
@bitshiftr I have implemented date selection feature if you're still looking for it

**Comment by bitshiftr** [comment]
is this in the latest push? For the auto-booking branch, I am still seeing that last push was 14 hours ago

**Comment by pallupz** [comment]
main branch

**Comment by pallupz** [comment]
all updates from now on will be on main. its difficult to maintain two branches
